[package]
name = "neotest_common"
version = "0.1.0"
edition = "2021"
keywords = ["test", "fixture"]
license = "MIT OR Apache-2.0"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
