name: Deploy to crates.io
on:
  release:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: ./.github/actions/rust-toolchain

      - name: Login to cargo
        run: cargo login ${{ secrets.CARGO_API_TOKEN }}

      - name: Publish neotest-common
        working-directory: neotest-common
        run: cargo publish

      - name: Publish neotest-macros
        working-directory: neotest-macros
        run: cargo publish

      - name: Publish neotest
        working-directory: neotest
        run: cargo publish

