name: Deploy Github Pages
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  generate:
    name: Generate cargo docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust Toolchain (Stable)
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Generate Documentation
        run: |
          cargo doc --no-deps --document-private-items
          echo "<meta http-equiv=\"refresh\" content=\"0; url=neotest\">" > target/doc/index.html
          cp -r target/doc ./docs

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./target/doc

  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    needs: generate

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Upload GH Pages
        id: deployment
        uses: actions/deploy-pages@v1
